### ISSUE TITLE
Spring Cloud Contract doesn't work with Spring Boot 1.4.1

### ISSUE THREAD

**Issue by jfcorugedo** [spring-cloud/spring-cloud-contract#126]
I'm trying to build a basic example using Spring Cloud Contract capabilities.

Using Spring Tool Suite wizard, to add Spring Cloud Contract I have to select Spring-Boot version 1.4.1 or higher.

However when I create a project that uses Spring Boot 1.4.1 and Spring Contract 1.0.1.RELEASE, all my integration tests fails with the following error:

    java.lang.NoClassDefFoundError: org/springframework/boot/SpringBootConfiguration

I've also tried to download the official examples ([server][1] and [consumer][2] projects).

Both of them works perfectly, but they're using a non stable version of Spring-Boot:

    <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.0.BUILD-SNAPSHOT</version>
		<relativePath />
	</parent>

When I try to change this version to 1.4.1, both of them fails with the same error.

Does anyone know how to configure Spring Cloud Contract? Is there any example over there?

  [1]: https://github.com/spring-cloud/spring-cloud-contract/tree/master/samples/standalone/dsl/http-server
  [2]: https://github.com/spring-cloud/spring-cloud-contract/tree/master/samples/standalone/dsl/http-client

**Comment by marcingrzejszczak** [comment]
That's interesting... Can you try https://github.com/spring-cloud-samples/github-analytics/blob/master/build.gradle or https://github.com/spring-cloud-samples/github-webhook/blob/master/pom.xml ? I see that we're using Boot 1.4.1 with SC-Contract 1.0.0. Can you try bumping them to 1.0.1 and see if it's working fine?

**Comment by jfcorugedo** [comment]
I've tried your project but it didn't work either.

However I've found the problem. It was really wierd!

After deleting my entire repository folder and download again spring boot dependencies, it worked again.

**Comment by marcingrzejszczak** [comment]
That's really strange. Good that it's working fine though :)
