### PR TITLE
Issues #110 user pass

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
Continued from https://github.com/spring-cloud/spring-cloud-contract/pull/142

@mogronalol @yacekmm

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@yacekmm - once this builds can you check out the branch, build it locally, pass your username and password via `stubrunner.username` and `stubrunner.password` properties in Spring to check if it's working correctly?

**Comment by yacekmm** [comment]
I get 

> java.lang.NoClassDefFoundError: org/springframework/cloud/contract/verifier/messaging/MessageVerifier

when running cdc test with this branch - I did not change anything - just ran the same code that worked on 1.0.2.RELEASE. stub-runner build passed, but the runtime exception occured

**Comment by marcingrzejszczak** [comment]
@yacekmm when does this exception occur? Can you elaborate more on this?

**Comment by yacekmm** [comment]
Sure, I was hoping that this exception will occur also in your env. It happens on app startup, the context fails to start. Here are the logs: 

> [2016-12-05 13:06:36.457] ERROR [crown-service-      main] org.springframework.boot.SpringApplication   [838 ]: Application startup failed
java.lang.IllegalStateException: Could not evaluate condition on org.springframework.cloud.contract.stubrunner.spring.cloud.StubRunnerSpringCloudAutoConfiguration#stubRunnerDiscoveryClientWrapper due to org/springframework/cloud/contract/verifier/messaging/MessageVerifier not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:55)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:111)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.AutoConfigureReportTestExecutionListener.prepareTestInstance(AutoConfigureReportTestExecutionListener.java:46)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/contract/verifier/messaging/MessageVerifier
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:612)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:683)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:627)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:597)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1450)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:980)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:289)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanType(BeanTypeRegistry.java:278)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:259)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:179)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:168)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:136)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:81)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 47 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.contract.verifier.messaging.MessageVerifier
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 67 common frames omitted

stub-runner compilation ended with success. I use it with `'org.springframework.cloud:spring-cloud-contract-wiremock:1.0.2.RELEASE'` in `build.gradle`

**Comment by marcingrzejszczak** [comment]
Crap - on CircleCI it's working fine - https://github.com/spring-cloud/spring-cloud-contract/commit/6a6849b41ff812b9d9f5ec6be7471140e4d7f120 

It works on my machine too :/

**Comment by marcingrzejszczak** [comment]
Which module is failing to be built? Or is it your application that is failing?

**Comment by yacekmm** [comment]
It builds. It just fails to start context in tests. I managed to fix it. I had to add explicitly those dependencies:

> testCompile group: 'org.springframework.cloud', name: 'spring-cloud-contract-verifier', version: '1.0.2.RELEASE'
    testCompile group: 'org.eclipse.aether', name: 'aether-api', version: '1.1.0'
    testCompile group: 'org.eclipse.aether', name: 'aether-impl', version: '1.1.0'
    testCompile group: 'org.eclipse.aether', name: 'aether-transport-file', version: '1.1.0'
    testCompile group: 'org.eclipse.aether', name: 'aether-transport-http', version: '1.1.0'
    testCompile group: 'org.eclipse.aether', name: 'aether-connector-basic', version: '1.1.0'
    testCompile group: 'org.apache.maven', name: 'maven-aether-provider', version: '3.3.9'

I hoped they were included in stub-runner.

Good news is that stubs are successfully downloaded from password protected maven repo

**Comment by marcingrzejszczak** [comment]
Yay :D 👍  🔥

**Comment by mogronalol** [comment]
Oops, sorry for having to disappear for so long.  Thanks for fixing this, it's really helpful for us internally.

Random side note - I always end up arguing with people about `toString` on the various projects I've worked on.  Basically I find using reflection better, because if you add or remove fields then the method's automatically kept up to date.  Never really been that convinced about the performance argument, in the sense that there's usually not a performance requirement to justify not using reflection.  What do you think? Just because I've noticed some of the `toString` methods were becoming quite verbose.

**Comment by marcingrzejszczak** [comment]
Yeah they are verbose. AFAIR there's the Reflections to String builder from commons but we're not trying to rely on any of their stuff. If I had a business project I'd use Lombok and got over this ;)

**Comment by mogronalol** [comment]
Out of interest, why can't you depend on apache commons? Why would it be so much of a problem as a transitive dependency?
