### ISSUE TITLE
Contract with XML body in HTTP/ REST

### ISSUE THREAD

**Issue by KonradEichstaedt** [spring-cloud/spring-cloud-contract#322]
If I trying to create a Contract Groovy File using a POST request with an XML body it always failed because the Contract.make destroyed the XML tags using JSON encoding. Can I disable this or exist an workaround?

**Comment by marcingrzejszczak** [comment]
XML is not supported at all unfortunately.

**Comment by KonradEichstaedt** [comment]
Because we have several REST Interfaces using XML instead of JSON , it is possible that you take this issue as change request for a comming release? Many Thanks

**Comment by rontron** [comment]
+1

**Comment by Fitzoh** [comment]
@KonradEichstaedt (and @rontron / @ronnymikalsen since you 👍'd), any chance you have an example of what you're trying to do?

Are you just looking for a simple-ish equality comparison or fuller DSL support?
If you can think of an example of an API you might like to see that would be great.

**Comment by ketanprajapati88** [comment]
+1 for XML support  in Spring Cloud Contract. It seems this is cool offering for JSON APIs, wanted to have for XML Apis too.

**Comment by sdulebskiy** [comment]
+1

**Comment by pandeymradul** [comment]
+1

**Comment by marcingrzejszczak** [comment]
We've created a simplified XML support via RestDocs. You can use it until then. Also you can just add `+1` at the top instead of adding comments.

**Comment by marcingrzejszczak** [comment]
Done here - https://github.com/spring-cloud/spring-cloud-contract/issues/647

producer example here:
https://github.com/spring-cloud/spring-cloud-contract/blob/master/samples/standalone/restdocs/http-server/src/test/java/com/example/fraud/XmlStubGeneratorTests.java

assembly here: 
https://github.com/spring-cloud/spring-cloud-contract/blob/master/samples/standalone/restdocs/http-server/src/assembly/stub.xml#L25-L31 

Client via Stub Runner here: 
https://github.com/spring-cloud/spring-cloud-contract/blob/master/samples/standalone/restdocs/http-client/src/test/java/com/example/loan/XmlServiceUsingStubRunnerTests.java

**Comment by ketanprajapati88** [comment]
Thanks a lot @marcingrzejszczak. I will try this support. XMLStubGeneratorTest example puts hard coded XML in test . Does this mechanism support auto generated test like what it does for JSON based on plain contract file?

**Comment by marcingrzejszczak** [comment]
> Does this mechanism support auto-generated test like what it does for JSON based on plain contract file?

not yet. Currently, to allow any form of XML support we've decided to add basic support via Rest Docs. We will be working on XML in 2.1.0.

**Comment by ketanprajapati88** [comment]
@marcingrzejszczak any idea on release date for 2.1.0?

**Comment by marcingrzejszczak** [comment]
Currently not. We've just released 2.0.0. Check this page for more info https://github.com/spring-cloud/spring-cloud-release/milestones it will contain that information

**Comment by ketanprajapati88** [comment]
@marcingrzejszczak will watch for release 2.1.0. Till then RestDocs support is good addition to spring cloud contract. Thanks again for sharing details.

**Comment by prasadvijayjoshi** [comment]
@marcingrzejszczak , Thanks for the update on XML support. I am getting some trouble extracting the cloned zip file on Windows from Master.  Is there anyone got success ?

**Comment by prasadvijayjoshi** [comment]
@marcingrzejszczak  I am able to clone it and got it working now. I see its using Spring boot 2.0.3 Release.
Could you please share similar example using Spring Boot 1.5.2 (which we use in my company project) as I am facing Class not found exception when I try to implement same example in my project
(java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/source/ConfigurationPropertySource) 
Thank you

**Comment by marcingrzejszczak** [comment]
@prasadvijayjoshi it's been added only for Boot 2.0 based version.

**Comment by ketanprajapati88** [comment]
@marcingrzejszczak Example is only for Boot 2.0 + which is fine but does that mean Spring Cloud Contract XML support needs minimum 2.0 boot version?

+ @prasadvijayjoshi

**Comment by marcingrzejszczak** [comment]
@ketanprajapati88 from what I see that's also added in 1.2.5 (https://github.com/spring-cloud/spring-cloud-contract/blob/1.2.x/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockSnippet.java) and the issue https://github.com/spring-cloud/spring-cloud-contract/issues/647

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by marcingrzejszczak** [comment]
Lol :)

**Comment by ketanprajapati88** [comment]
@marcingrzejszczak , as now Spring Cloud Contract 2.1.0 M2 released, wanted to ask my previous question again.

"Does 2.1.0 M2 started supporting automated generated test for XML Apis along with already supported JSON API?

Your previous comment:
not yet. Currently, to allow any form of XML support we've decided to add basic support via Rest Docs. We will be working on XML in 2.1.0.

Can you please comment on this?

**Comment by OlgaMaciaszek** [comment]
@ketanprajapati88  We are currently working on it.

**Comment by ketanprajapati88** [comment]
Thanks @OlgaMaciaszek . Does that mean auto generated test for XML API are not supported in 2.1.0 M2? Can you share which version will it be available? + @marcingrzejszczak

**Comment by OlgaMaciaszek** [comment]
There are not supported as of yet. We are working on adding them to 2.1.0 RC1 which should come out in 1 week. Can't promise 100% we will manage to finish it by then - but we are trying to get it done.

**Comment by hustleone** [comment]
Hi!
I had the same issue #828 but when i have changed version to 2.0.2 my xml body started to be generated correctly. I'm interested why you commit changes to 2.1.0 version but 2.0.2 seems work fine.

**Comment by OlgaMaciaszek** [comment]
Since most of the feature request were related to using XML with HTTP/ REST, we have implemented this for now. A separate issue has been created to tackle XML for messaging: https://github.com/spring-cloud/spring-cloud-contract/issues/853 . It will only be implemented, however, if there is enough interest in the community. So please upvote or comment in that issue if that's a functionality that would be useful for you.

**Comment by atidjani** [comment]
Hi,
is there any documentation of how to write contracts which verify XML responses ?
I couldn't find it anywhere.

Thanks

**Comment by hustleone** [comment]
> Hi,
> is there any documentation of how to write contracts which verify XML responses ?
> I couldn't find it anywhere.
> 
> Thanks

Hi!

My one looks like:
```Contract.make {
	request {
		method(HttpMethods.HttpMethod.POST)
		url('/CS/EQ/WSCustomerAddress/WSCustomerAddress11')
		body(
			equalToXml(
				file('AKJUZB-request.xml')
			)
		)
	}
	response {
		status(200)
		headers {
			header(contentType(), "text/xml; charset=utf-8")
		}
		body(file('AKJUZB-response.xml'))
	}
}```
